### ISSUE TITLE
IPString2Long和Long2IPString 能否支持IPV6？

### ISSUE THREAD

**Issue by YouZhengChuan** [thinkeridea/go-extend#1]

**Comment by thinkeridea** [comment]
抱歉暂时只支持IPV4

**Comment by thinkeridea** [comment]
https://www.ipaddressguide.com/ipv6-to-decimal  这个网址可以转换

2001:4860:4860::8888   => 42541956123769884636017138956568135816

这个数值已经操过普通数字的大小了，ipv4是4字节， ipv6是16字节，我现在能想到的是用两个uint64来表示ipv6的数值, 但是这并不是很理想

**Comment by thinkeridea** [comment]
```go
ip := net.ParseIP("2001:4860:4860::8888").To16()

	bigNum := &big.Int{}
	bigNum.SetBytes(ip)
	fmt.Println(bigNum.String())

	fmt.Println("42541956123769884636017138956568135816")
```


我写了一个小的demo， 保持和这个网站一致的结构，但是这个输出只是一个字符串，可能对排序的帮助并不大

**Comment by YouZhengChuan** [comment]
我自己实现了一个简单的memSearch方式。但是目前只能读取txt文本文件的ip库，格式：
ipv6|ipv6 mask|*|*|本地网络|*|*
